=== prototypefund/growing-futures-admin-app/src/data/schemas/productSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "A product that can be added to a CSA delivery",
    "properties": {
        "categories": {
            "description": "A url to an icon for this vegetable 256x256",
            "items": {
                "type": "string"
            },
            "minItems": 1,
            "type": "array",
            "uniqueItems": true,
            "xDisplay": "Categories",
            "xRef": "categories",
            "xType": "multiSelect"
        },
        "image": {
            "description": "A url to an icon for this vegetable 256x256",
            "type": "string",
            "xDisplay": "Image"
        },
        "name": {
            "description": "The name of the product",
            "type": "string",
            "xDisplay": "Name"
        },
        "uid": {
            "description": "A unique ID for this item",
            "type": "string",
            "xDisplay": "UID",
            "xRestrictions": "read-only"
        },
        "unit": {
            "description": "The default unit used for this product",
            "type": "string",
            "xDisplay": "Unit"
        }
    },
    "required": [
        "name",
        "categories",
        "unit"
    ],
    "title": "product",
    "type": "object",
    "xUidPrefix": "product"
}

=== prototypefund/growing-futures-admin-app/tests/unit/data/products.json
[
    {
        "categories": [
            "salat"
        ],
        "image": "/path/to/image",
        "name": "Eichblattsalat",
        "uid": "product0001",
        "unit": "p"
    },
    {
        "categories": [
            "wurzelgemuese"
        ],
        "image": "",
        "name": "Meerrettich",
        "uid": "product0002",
        "unit": "g"
    },
    {
        "categories": [
            "salat"
        ],
        "image": "",
        "name": "Chinesische Keule",
        "uid": "product0003",
        "unit": "g"
    }
]
