=== prototypefund/growing-futures-admin-app/src/data/schemas/userSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "user",
    "description": "A user",
    "type": "object",
    "properties": {
        "username": {
            "description": "The username of the user",
            "type": "string",
            "xDisplay": "Benutzername"
        },
        "name": {
            "description": "The full name of the user",
            "type": "string",
            "xDisplay": "Name"
        },
        "depot": {
            "type": "string",
            "description": "The default depot used for this user",
            "xDisplay": "Depot",
            "xType": "singleSelect",
            "xRef": "depot"
        },
        "shareType": {
            "type": "string",
            "description": "The default depot used for this user",
            "xDisplay": "Anteilstyp",
            "xType": "singleSelect",
            "xRef": "shareType"
        }
    },
    "required": [
        "name",
        "username",
        "depot",
        "shareType"
    ]
}

=== prototypefund/growing-futures-admin-app/src/data/mock-data/users.json
[
  {
    "username": "johndoe",
    "name": "John Doe",
    "shareType": "small",
    "depot": "Krummennaab"
  },
  {
    "username": "aa",
    "name": "Alex Awesome",
    "shareType": "big",
    "depot": "Weiden"
  },
  {
    "username": "jens",
    "name": "Udo Oinki",
    "shareType": "big",
    "depot": "Krummennaab"
  },
  {
    "username": "boris",
    "name": "Da Boris",
    "shareType": "small",
    "depot": "Weiden"
  }

]
